language: php

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1

before_script:
  - chmod 777 -R storage
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  # - cat .env
  - npm install
  - npm run dev
  # - php artisan migrate --seed --no-interaction
  # - ls -la

script:
  - vendor/bin/phpunit

notifications:
  # slack:
  #   on_success: never
  #   on_fail: always
  email:
    - jomwashighadi@gmail.com